# Generated by Django 3.0.1 on 2020-01-06 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200105_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_vk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
