# Generated by Django 3.0.1 on 2020-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200107_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
