# Generated by Django 3.0.1 on 2019-12-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='use_proxy',
            new_name='need_proxy',
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('port', models.CharField(max_length=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
