# Generated by Django 3.0.1 on 2020-01-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200109_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
