# Generated by Django 3.0.1 on 2020-01-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user-default.jpg', upload_to='user_image'),
        ),
    ]
