# Generated by Django 3.0.1 on 2020-02-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200119_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_login',
        ),
    ]
