# Generated by Django 2.2.7 on 2020-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_vk_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_login',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
