# Generated by Django 2.2.7 on 2020-02-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200212_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipstatus',
            options={'verbose_name': 'Relationship Status', 'verbose_name_plural': 'Relationships Statuses'},
        ),
    ]
