# Generated by Django 2.2.10 on 2020-05-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200212_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user-default.png', upload_to='user_image'),
        ),
    ]
