# Generated by Django 2.2.10 on 2020-05-31 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200513_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_songs_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
