# Generated by Django 3.0.1 on 2020-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='from_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
