# Generated by Django 2.2.10 on 2020-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegrambotlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotlogs',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
