# Generated by Django 2.2.10 on 2020-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegrambotlogs_exception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotlogs',
            options={'ordering': ('created_at',)},
        ),
    ]
