# Generated by Django 2.2.10 on 2020-05-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200515_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotlogs',
            options={'ordering': ('-created_at',), 'verbose_name': 'Telegram Bot Log', 'verbose_name_plural': 'Telegram Bot Logs'},
        ),
    ]
