# Generated by Django 2.2.13 on 2020-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_telegramlogs_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlogs',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
