# Generated by Django 3.0.1 on 2019-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=16, null=True)),
                ('use_proxy', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
    ]
