# Generated by Django 2.2.10 on 2020-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='0.0.1', max_length=10)),
                ('details', models.TextField(default='Your version is out of date, please upgrade to a new version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
