# Generated by Django 3.0.1 on 2019-12-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequestsList',
        ),
    ]
