# Generated by Django 3.0.1 on 2019-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191218_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_id',
        ),
        migrations.AddField(
            model_name='song',
            name='download',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
