# Generated by Django 3.0.1 on 2019-12-21 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_song_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
