# Generated by Django 2.2.7 on 2020-02-13 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_auto_20200212_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='users_ignore',
            field=models.ManyToManyField(blank=True, related_name='song_users_ignore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='song_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
