# Generated by Django 2.2.13 on 2020-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200529_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ignore_time',
            field=models.BooleanField(default=False),
        ),
    ]
