# Generated by Django 2.2.10 on 2020-04-22 23:03

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('home', '0002_auto_20200423_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='file',
        ),
        migrations.AddField(
            model_name='myapp',
            name='android_app',
            field=filer.fields.file.FilerFileField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='android', to='filer.File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myapp',
            name='ios_app',
            field=filer.fields.file.FilerFileField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ios', to='filer.File'),
            preserve_default=False,
        ),
    ]
