# Generated by Django 2.2.10 on 2020-04-22 23:24

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200423_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='android_app',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='android', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='ios_app',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ios', to='filer.File'),
        ),
    ]
