# Generated by Django 2.2.10 on 2020-04-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200423_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapp',
            old_name='details',
            new_name='update_details',
        ),
    ]
