# Generated by Django 2.2.10 on 2020-04-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200424_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='android_app',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='ios_app',
            field=models.URLField(blank=True, null=True),
        ),
    ]
