# Generated by Django 2.2.10 on 2020-04-29 21:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200425_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='update_details',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='version',
        ),
        migrations.AlterField(
            model_name='myapp',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='x.x.x', max_length=10)),
                ('details', ckeditor.fields.RichTextField(default='Bug fixes')),
                ('update_details', models.TextField(default='Your version is out of date, please upgrade to a new version.')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='home.MyApp')),
            ],
        ),
    ]
