# Generated by Django 2.2.10 on 2020-04-29 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200430_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversions',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
