# Generated by Django 2.2.13 on 2020-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200504_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversions',
            name='web_version',
            field=models.URLField(blank=True, null=True),
        ),
    ]
