# Generated by Django 2.2.10 on 2020-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeFormats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, choices=[('song', 'Song'), ('video', 'Video')], default='song', max_length=10, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('creator', models.CharField(blank=True, max_length=511, null=True)),
                ('alt_title', models.CharField(blank=True, max_length=511, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('image', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=511, null=True)),
                ('track', models.CharField(blank=True, max_length=511, null=True)),
                ('album', models.CharField(blank=True, max_length=511, null=True)),
                ('webpage_url', models.URLField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('formats', models.ManyToManyField(blank=True, to='youtube_saver.YoutubeFormats')),
            ],
        ),
    ]
