# Generated by Django 2.2.10 on 2020-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeposts',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
