# Generated by Django 2.2.10 on 2020-04-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0002_youtubeposts_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeformats',
            options={'verbose_name': 'YoutubeFormat', 'verbose_name_plural': 'YoutubeFormats'},
        ),
        migrations.AlterModelOptions(
            name='youtubeposts',
            options={'verbose_name': 'YoutubePost', 'verbose_name_plural': 'YoutubePosts'},
        ),
    ]
