# Generated by Django 2.2.10 on 2020-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0003_auto_20200402_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeformats',
            name='format',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
