# Generated by Django 2.2.10 on 2020-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0004_auto_20200402_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeformats',
            name='file_type',
            field=models.CharField(blank=True, choices=[('song', 'Song'), ('video', 'Video'), ('video_song', 'Video with Audio')], default='song', max_length=10, null=True),
        ),
    ]
