# Generated by Django 2.2.10 on 2020-04-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0005_auto_20200404_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeformats',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='youtubeformats',
            name='format',
        ),
        migrations.RemoveField(
            model_name='youtubeformats',
            name='size',
        ),
        migrations.RemoveField(
            model_name='youtubeformats',
            name='url',
        ),
        migrations.RemoveField(
            model_name='youtubeposts',
            name='formats',
        ),
    ]
