# Generated by Django 2.2.10 on 2020-04-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0006_auto_20200430_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeFormats',
        ),
    ]
