# Generated by Django 2.2.10 on 2020-06-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0008_downloadyoutubemp3shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadyoutubemp3shortlink',
            options={'verbose_name': 'MP3 Short Link', 'verbose_name_plural': 'MP3 Short Links'},
        ),
        migrations.AlterModelOptions(
            name='youtubeposts',
            options={'verbose_name': 'Youtube Post', 'verbose_name_plural': 'Youtube Posts'},
        ),
    ]
