# Generated by Django 2.2.10 on 2020-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0009_auto_20200617_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadyoutubemp3shortlink',
            name='original_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
