# Generated by Django 2.2.10 on 2020-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0010_downloadyoutubemp3shortlink_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadyoutubemp3shortlink',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
