# Generated by Django 2.2.10 on 2020-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0011_downloadyoutubemp3shortlink_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadyoutubemp3shortlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
