# Generated by Django 2.2.10 on 2020-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0012_auto_20200617_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadyoutubemp3shortlink',
            name='video_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downloadyoutubemp3shortlink',
            name='slug',
            field=models.SlugField(),
        ),
    ]
